version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: build/apache/php-7.4/Dockerfile
    ports:
      - "8080:80"
      - "9001:9000" # xdebug
    volumes:
      - ./src:/var/www/html
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.npm:/var/www/.npm
      - ./.docker/php/conf.d/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    networks:
      - magento-network

  db:
    restart: always
    image: mysql:8.0.27
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/initdb:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
    networks:
      - magento-network

  redis:
    image: redis
    expose:
     - "6379"
    networks:
      - magento-network

  redis-session:
    image: redis
    expose:
     - "6379"
    networks:
      - magento-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magento-network

  varnish:
    build:
      context: .
      dockerfile: build/varnish/Dockerfile
    hostname: varnish
    ports:
      - "80:80"
    networks:
      - magento-network
    depends_on:
      - apache
    volumes:
      - ./build/varnish/varnish6.vcl:/etc/varnish/default.vcl
      - ./build/varnish/varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=64M

  elasticsearch:
    build:
      context: .
      dockerfile: build/elasticsearch/Dockerfile
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=node-1
      - cluster.initial_master_nodes=node-1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - magento-network

networks:
  magento-network:
    driver: bridge

volumes:
  dbdata:
  elasticsearchdata:
