global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "varnish"
    static_configs:
      - targets: ["varnish:9131"]

#remote_write:
#  - url: "localhost:9090/receive"
#    basic_auth:
#      username: "admin"
#      password: "admin"
